spring.application.name=simulador-mundial
server.port=8080

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mundial_umg
spring.datasource.username=postgres
spring.datasource.password=fc17181931

# Le decimos a Spring Boot que ejecute el schema y los inserts al iniciar
spring.sql.init.mode=always