spring.application.name=simulador-mundial
# Puerto donde correrá nuestro servidor web
server.port=8080

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mundial_umg
spring.datasource.username=postgres
spring.datasource.password=fc17181931

# ¡LA MAGIA DE LA POO! Esto crea las tablas automáticamente basadas en tus clases de Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true