spring.application.name=simulador-mundial
server.port=8080

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mundial_umg
spring.datasource.username=postgres
spring.datasource.password=fc17181931

# ==============================================================
# NUEVA CONFIGURACIÓN JDBC (Sin magia JPA)
# ==============================================================
# 1. Siempre inicializar la base de datos
spring.sql.init.mode=always
# 2. Primero: Ejecuta este archivo para crear las tablas
spring.sql.init.schema-locations=classpath:schema.sql
# 3. Segundo: Ejecuta este archivo para insertar los países/jugadores
spring.sql.init.data-locations=classpath:data.sql
# 4. Si hay un error creando tablas (porque ya existen), que no detenga el proyecto
spring.sql.init.continue-on-error=true